# Generated by Django 5.2.8 on 2025-12-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_category_name_en_category_category_name_ky_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_name_ky",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_ky",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_name_ky",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="subCategory_name_ky",
        ),
    ]
