# Generated by Django 5.2.8 on 2025-12-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_category_category_name_ky_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="review",
            name="text",
        ),
        migrations.AddField(
            model_name="review",
            name="reviewText",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, null=True, upload_to="category_image/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_video",
            field=models.FileField(blank=True, null=True, upload_to="video/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_photo",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="product_image/"),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_review",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="subCategory_name",
            field=models.CharField(max_length=54),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="subCategory_name_en",
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="subCategory_name_ru",
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatar/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("gold", "gold"),
                    ("silver", "silver"),
                    ("bronze", "bronze"),
                    ("simple", "simple"),
                ],
                default="simple",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subCategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sub",
                to="store.subcategory",
            ),
            preserve_default=False,
        ),
    ]
